---
- hosts: localhost
  tasks:
  - name: Remove dashboard release and waiting suppression ending
    kubernetes.core.helm:
      name: dashboard
      release_namespace: default
      state: absent
      wait: true
  - name: remove admin user
    kubernetes.core.k8s:
      state: absent
      src: ./kube/admin-user.yml
  - name: "remove kubernetes python package"
    pip:
      name: kubernetes
      state: absent
